const state={courses:[],selected:new Set(JSON.parse(localStorage.getItem('quick-schedule-selected')||'[]')),query:'',queryTokens:[],subject:'',type:'',view:'week',week:Number(localStorage.getItem('quick-schedule-week')||2)};
const dayNames=['周一','周二','周三','周四','周五','周六','周日'];
const palette=['','green','orange','pink'];
const periodTimes={1:'08:00–08:45',2:'08:55–09:40',3:'10:00–10:45',4:'10:55–11:40',5:'14:00–14:45',6:'14:55–15:40',7:'16:00–16:45',8:'16:55–17:40',9:'18:30–19:15',10:'19:25–20:10',11:'20:20–21:05',12:'21:15–22:00',13:'22:10–22:55'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseTime(t){const m=String(t).match(/周([一二三四五六日天])\s*\(([^)]+)\)/); if(!m)return null; const map={一:0,二:1,三:2,四:3,五:4,六:5,日:6,天:6}; const nums=m[2].split('-').map(Number); return {day:map[m[1]],start:nums[0]||1,end:nums[1]||nums[0]||1};}
function credit(c){const m=String(c.hoursCredits||'').match(/\/(\d+(?:\.\d+)?)/);return m?Number(m[1]):0}
function creditGroup(c){const t=String(c.type||''),n=String(c.name||'');if(n.includes('工程伦理'))return 'nonDegreeRequired';if(['研讨课','实验课','实践课'].some(x=>t.includes(x))||t.includes('讲座')||n.includes('讲座'))return 'professionalElective';if(t==='公共选修课')return 'publicElective';if(t==='公共必修课')return 'publicDegree';return 'professionalDegree'}
const creditRules={publicDegree:{label:'公共必修学位课',target:7,desc:'学位课程'},professionalDegree:{label:'专业学位课',target:12,desc:'核心课 + 专业课'},publicElective:{label:'公共选修课',target:2,desc:'公共选修'},professionalElective:{label:'专业选修课',target:2,desc:'研讨 / 实验 / 实践 / 讲座'},nonDegreeRequired:{label:'公共必修非学位课',target:1,desc:'工程伦理'} };
let selectedCategory='all';
function renderCreditProgress(){const sums=Object.fromEntries(Object.keys(creditRules).map(k=>[k,0]));selectedCourses().forEach(c=>sums[creditGroup(c)]+=credit(c));$('#creditTotalLabel').textContent=`已计入 ${Object.values(sums).reduce((a,b)=>a+b,0).toFixed(1).replace('.0','')} 学分`;$('#creditProgress').innerHTML=Object.entries(creditRules).map(([k,r])=>{const v=sums[k],pct=Math.min(100,v/r.target*100);return `<div class="credit-item"><div class="credit-item-head"><span>${r.label}</span><b>${v.toFixed(1).replace('.0','')} / ${r.target} 学分</b></div><div class="progress"><i style="width:${pct}%"></i></div><small>${v>=r.target?'已达标':`还需 ${(r.target-v).toFixed(1).replace('.0','')} 学分`} · ${r.desc}</small></div>`}).join('')}
function selectedRows(){return selectedCourses().filter(c=>selectedCategory==='all'||creditGroup(c)===selectedCategory)}
function renderSelectedTable(){const cats=[['all','全部'],...Object.entries(creditRules).map(([k,v])=>[k,v.label])];$('#categoryTabs').innerHTML=cats.map(([k,label])=>`<button class="category-tab ${selectedCategory===k?'active':''}" data-cat="${k}">${label}<b>${k==='all'?selectedCourses().length:selectedCourses().filter(c=>creditGroup(c)===k).length}</b></button>`).join('');document.querySelectorAll('.category-tab').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;renderSelectedTable()});const rows=selectedRows();$('#selectedTableBody').innerHTML=rows.length?rows.flatMap(c=>c.sessions.map(s=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.code)}</td><td>${creditRules[creditGroup(c)]?.label||'其他'}</td><td>${esc(s.time||'')}${s.parsed?`<small>${periodText(s.parsed)}</small>`:''}</td><td>${esc(s.weeks||'')}</td><td>${esc(s.location||'')}</td><td>${esc(c.teacher||'待定')}</td><td><button class="remove-mini" data-id="${esc(c.id)}">移出</button></td></tr>`)).join(''):'<tr><td colspan="8" class="table-empty">当前分类暂无已选课程</td></tr>';document.querySelectorAll('.remove-mini').forEach(b=>b.onclick=()=>toggleCourse(b.dataset.id))}
function exportExcel(scope){const rows=(scope==='all'?selectedCourses():selectedRows()).flatMap(c=>c.sessions.map(s=>[c.name,c.code,creditRules[creditGroup(c)]?.label||'其他',s.time||'',periodText(s.parsed),s.weeks||'',s.location||'',c.teacher||'待定']));if(!rows.length){toast('当前没有可导出的课程');return}const head=['课程名称','课程代码','培养分类','原始上课时间','具体钟点','周次','地点','教师'];const escCell=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const html=`<html><head><meta charset="UTF-8"></head><body><table><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(x=>`<td>${escCell(x)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const blob=new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`804班已选课程_${scope==='all'?'全部':creditRules[selectedCategory]?.label||'分类'}.xls`;a.click();URL.revokeObjectURL(a.href);toast(`已导出 ${rows.length} 条课程安排`)}
function periodText(p){if(!p)return '';return p.start===p.end?periodTimes[p.start]||`第${p.start}节`:`${periodTimes[p.start]?.split('–')[0]||''}–${periodTimes[p.end]?.split('–')[1]||''}`}
function normalizeCourse(c,i){return {...c,id:c.code||String(i),sessions:(c.sessions||[]).map(s=>({...s,parsed:parseTime(s.time)}))}}
function selectedCourses(){return state.courses.filter(c=>state.selected.has(c.id))}
function normalizeText(v){return String(v??'').toLowerCase().replace(/[\s\u3000\-_/\\,，、;；|]+/g,'')}
function weeksFor(text){const nums=[...String(text??'').matchAll(/\d+/g)].map(m=>Number(m[0]));const out=new Set();if(!nums.length)return out;for(let i=0;i<nums.length;i+=2){const a=nums[i],b=nums[i+1]&&nums[i+1]>a?nums[i+1]:a;for(let n=a;n<=b;n++)out.add(n)}return out}
function conflicts(){const out=[]; const arr=selectedCourses(); arr.forEach((a,i)=>{arr.slice(i+1).forEach(b=>{a.sessions.forEach(sa=>{b.sessions.forEach(sb=>{const x=sa.parsed,y=sb.parsed;if(x&&y&&x.day===y.day&&Math.max(x.start,y.start)<=Math.min(x.end,y.end))out.push([a,b,dayNames[x.day],`${Math.max(x.start,y.start)}-${Math.min(x.end,y.end)}节`])})})})}); return out}
function populateFilters(){const subjects=[...new Set(state.courses.map(c=>c.subject).filter(Boolean))].sort(); const types=[...new Set(state.courses.map(c=>c.type).filter(Boolean))].sort(); $('#subjectFilter').innerHTML='<option value="">全部学科</option>'+subjects.map(x=>`<option>${esc(x)}</option>`).join(''); $('#typeFilter').innerHTML='<option value="">全部课程性质</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('')}
function filtered(){const tokens=state.queryTokens.length?state.queryTokens:[state.query]; return state.courses.filter(c=>{const hay=[c.name,c.code,c.english,c.teacher].map(normalizeText); const match=!tokens.some(Boolean)||tokens.some(t=>hay.some(x=>x.includes(normalizeText(t)))); return match&&(!state.subject||c.subject===state.subject)&&(!state.type||c.type===state.type)})}
function renderCourses(){const list=filtered(); const bulk=state.queryTokens.length>1; $('#resultHint').textContent=`共 ${state.courses.length.toLocaleString()} 门，当前显示 ${Math.min(list.length,80)} 门${bulk?` · 已识别 ${state.queryTokens.length} 个粘贴项`:''}`;
 $('#courseList').innerHTML=list.slice(0,80).map(c=>{const sel=state.selected.has(c.id); const clash=sel&&conflicts().some(x=>x[0].id===c.id||x[1].id===c.id); const times=[...new Set(c.sessions.map(s=>s.parsed&&periodText(s.parsed)).filter(Boolean))].join(' / '); return `<article class="course-item ${sel?'selected':''} ${clash?'conflicted':''}"><div class="course-top"><div><div class="course-name">${esc(c.name)}</div><div class="course-code">${esc(c.code)}</div></div><button class="course-action" data-id="${esc(c.id)}">${sel?'已加入':'加入'}</button></div><div class="course-meta"><span>◷ ${esc(c.hoursCredits||'')}</span><span>◷ ${esc(times||'时间待定')}</span><span>◉ ${esc(c.teacher||'待定')}</span><span>⌖ ${esc(c.subject||'')}</span></div></article>`}).join('')||`<div class="empty-state"><div class="empty-icon">⌕</div><h3>没有找到匹配课程</h3><p>换个关键词或清除筛选试试</p></div>`;
 $('#listFooter').innerHTML=(list.length>80?`<span>已显示前 80 门，请继续搜索缩小范围</span>`:'')+(bulk&&list.length?`<button class="bulk-add" id="bulkAdd">批量加入这 ${Math.min(list.length,80)} 门</button>`:''); document.querySelectorAll('.course-action').forEach(b=>b.onclick=()=>toggleCourse(b.dataset.id)); document.querySelectorAll('.course-item').forEach(el=>el.onclick=e=>{if(!e.target.closest('button'))showCourse(el.querySelector('.course-action').dataset.id)}); $('#bulkAdd')?.addEventListener('click',()=>{list.slice(0,80).forEach(c=>state.selected.add(c.id));persist();renderAll();toast(`已批量加入 ${Math.min(list.length,80)} 门课程`)})}
function toggleCourse(id){if(state.selected.has(id))state.selected.delete(id);else state.selected.add(id); persist(); renderAll();}
function persist(){localStorage.setItem('quick-schedule-selected',JSON.stringify([...state.selected]));}
function scheduleData(){const slots={}; selectedCourses().forEach((c,ci)=>c.sessions.forEach(s=>{const p=s.parsed;if(!p||!weeksFor(s.weeks).has(state.week))return; for(let n=p.start;n<=p.end;n++){const key=`${p.day}-${n}`;(slots[key]??=[]).push({course:c,session:s,ci})}}));return slots}
function renderSchedule(){const arr=selectedCourses(), clash=conflicts(); $('#selectedCount').textContent=arr.length; $('#creditCount').textContent=arr.reduce((a,c)=>a+credit(c),0).toFixed(1).replace('.0',''); $('#hourCount').textContent=arr.reduce((a,c)=>a+c.sessions.reduce((n,s)=>{const p=s.parsed;return n+(p?p.end-p.start+1:0)},0),0); $('#conflictCount').textContent=clash.length; renderCreditProgress(); $('#conflictBanner').classList.toggle('hidden',!clash.length); $('#conflictBanner').innerHTML=clash.length?`⚠ 发现 ${clash.length} 处时间冲突：${clash.slice(0,2).map(x=>`${esc(x[0].name)} 与 ${esc(x[1].name)}（${x[2]} ${x[3]}）`).join('；')}${clash.length>2?'…':''}`:'';
 if(!arr.length){$('#scheduleView').innerHTML='<div class="empty-state"><div class="empty-icon">▦</div><h3>你的课表还是空的</h3><p>从左侧课程库加入课程，这里会实时排好一周安排</p></div>';return}
 if(state.view==='list'){renderListView();return}
const slots=scheduleData(); let html='<div class="schedule-scroll"><div class="week-grid"><div class="corner"></div>'+dayNames.map((d,i)=>`<div class="day-head ${i===new Date().getDay()-1?'today':''}">${d}<small>${i+1}</small></div>`).join(''); for(let p=1;p<=13;p++){html+=`<div class="period-label"><b>${p}</b><small>${periodTimes[p]?.split('–')[0]||''}</small></div>`; for(let d=0;d<7;d++){const items=slots[`${d}-${p}`]||[]; html+=`<div class="day-cell">${items.map((x,j)=>{const bad=clash.some(c=>c[0].id===x.course.id||c[1].id===x.course.id);return `<div class="course-chip ${palette[x.ci%palette.length]} ${bad?'conflict':''}" data-id="${esc(x.course.id)}"><span>${esc(x.course.name)}</span><span class="room">${esc(x.session.location||'')}</span><span class="chip-time">${periodText(x.session.parsed)}</span></div>`}).join('')}</div>`}} html+='</div></div>'; $('#scheduleView').innerHTML=html; document.querySelectorAll('.course-chip').forEach(e=>e.onclick=()=>showCourse(e.dataset.id))}
function renderListView(){const byDay=Array.from({length:7},()=>[]); selectedCourses().forEach((c,ci)=>c.sessions.forEach(s=>{const p=s.parsed;if(p&&weeksFor(s.weeks).has(state.week))byDay[p.day].push({c,s,p,ci})})); $('#scheduleView').innerHTML='<div class="list-view">'+byDay.map((items,d)=>items.length?`<div class="list-day"><div class="list-day-head">${dayNames[d]}</div>${items.sort((a,b)=>a.p.start-b.p.start).map(x=>`<div class="list-class"><div class="list-time">第 ${x.p.start}-${x.p.end} 节<small>${periodText(x.p)}</small></div><div><strong>${esc(x.c.name)}</strong><small>${esc(x.s.location||'')} · ${esc(x.c.teacher||'待定')}</small></div></div>`).join('')}</div>`:'').join('')+'</div>'}
function showCourse(id){const c=state.courses.find(x=>x.id===id);if(!c)return; $('#modalContent').innerHTML=`<div class="code">${esc(c.code)}</div><h3>${esc(c.name)}</h3><div class="detail-grid"><div><label>课程性质</label>${esc(c.type||'—')}</div><div><label>系统分类</label>${creditRules[creditGroup(c)]?.label||'其他'}</div><div><label>教师</label>${esc(c.teacher||'待定')}</div><div><label>学时 / 学分</label>${esc(c.hoursCredits||'—')}</div><div><label>开课学科</label>${esc(c.subject||'—')}</div></div><div class="session-list"><label>上课安排</label>${c.sessions.map(s=>`<div class="session"><b>${esc(s.time||'—')}<small>${esc(s.parsed?periodText(s.parsed):'')}</small></b><span>${esc(s.weeks||'')} · ${esc(s.location||'地点待定')}</span></div>`).join('')}</div><button class="modal-cta" id="modalToggle">${state.selected.has(c.id)?'移出我的课表':'加入我的课表'}</button>`; $('#modalToggle').onclick=()=>{$('#courseModal').classList.add('hidden');toggleCourse(c.id)}; $('#courseModal').classList.remove('hidden')}
function renderAll(){renderCourses();renderSchedule();renderSelectedTable()}
function populateWeeks(){const s=$('#weekSelect');if(!s)return;s.innerHTML=Array.from({length:20},(_,i)=>`<option value="${i+1}">第 ${i+1} 周</option>`).join('');s.value=String(state.week);s.onchange=()=>{state.week=Number(s.value);localStorage.setItem('quick-schedule-week',state.week);renderSchedule()}}
async function init(){try{const response=await fetch('courses.json');if(!response.ok)throw new Error('课程数据请求失败');const data=await response.json();state.courses=data.map(normalizeCourse)}catch(e){if(Array.isArray(window.COURSE_DATA))state.courses=window.COURSE_DATA.map(normalizeCourse);else{$('#resultHint').textContent='课程数据读取失败，请使用网页服务器打开本页面';return}}state.selected=new Set([...state.selected].filter(id=>state.courses.some(c=>c.id===id)));populateFilters();populateWeeks();renderAll()}
$('#searchInput').oninput=e=>{state.query=e.target.value;renderCourses()}; $('#subjectFilter').onchange=e=>{state.subject=e.target.value;renderCourses()}; $('#typeFilter').onchange=e=>{state.type=e.target.value;renderCourses()}; $('#clearFilter').onclick=()=>{$('#searchInput').value='';$('#subjectFilter').value='';$('#typeFilter').value='';state.query=state.subject=state.type='';renderCourses()}; $('#demoBtn').onclick=()=>{state.selected=new Set(state.courses.slice(0,3).map(c=>c.id));persist();renderAll();toast('已加入 3 门示例课程')}; $('#printBtn').onclick=()=>window.print(); $('#shareBtn').onclick=()=>{const url=location.href.split('#')[0]+'#schedule='+btoa(unescape(encodeURIComponent(JSON.stringify([...state.selected]))));navigator.clipboard?.writeText(url);toast('分享链接已复制')}; document.querySelectorAll('.view-toggle button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;renderSchedule()}); $('#modalClose').onclick=()=>$('#courseModal').classList.add('hidden'); $('#courseModal').onclick=e=>{if(e.target.id==='courseModal')e.currentTarget.classList.add('hidden')}; window.onkeydown=e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#searchInput').focus()}};
$('#searchInput').addEventListener('input',()=>{if($('#searchInput').value!==`已粘贴 ${state.queryTokens.length} 个课号`){state.queryTokens=[];state.query=$('#searchInput').value;renderCourses()}});
$('#searchInput').addEventListener('paste',e=>{const raw=e.clipboardData?.getData('text')||'';const tokens=[...new Set(raw.split(/[\r\n\t ,，、;；|]+/).map(x=>x.trim()).filter(Boolean))];const hasSeparator=/[\r\n\t ,，、;；|]/.test(raw);if(tokens.length&&hasSeparator){e.preventDefault();state.query='';state.queryTokens=tokens;$('#searchInput').value=`已粘贴 ${tokens.length} 个课号`;renderCourses();toast(`已识别并去重 ${tokens.length} 个粘贴项`)}});
$('#exportCategoryBtn').onclick=()=>exportExcel('category'); $('#exportAllBtn').onclick=()=>exportExcel('all');
$('#clearFilter').addEventListener('click',()=>{state.queryTokens=[]});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
const hash=location.hash.match(/^#schedule=(.+)$/);if(hash){try{state.selected=new Set(JSON.parse(decodeURIComponent(escape(atob(hash[1])))))}catch{}} init();
